module.exports = {
	semi: true,
	singleQuote: true,
	trailingComma: 'all',
	printWidth: 90,
	tabWidth: 2,
	useTabs: true,
	bracketSpacing: true,
	bracketSameLine: true,
	endOfLine: 'lf',
	importOrder: [
		'^(react/(.*)$)|^(react$)',
		'^(next/(.*)$)|^(next$)',
		'<THIRD_PARTY_MODULES>',
		'',
		'^types$',
		'^@/types/(.*)$',
		'^@/config/(.*)$',
		'^@/lib/(.*)$',
		'^@repo/ui/(.*)$',
		'^@ui/components/(.*)$',
		'^@ui/sections/(.*)$',
		'^@ui/pages/(.*)$',
		'^@/stories/(.*)$',
		'^@/styles/(.*)$',
		'^@/app/(.*)$',
		'',
		'^[./]',
	],
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	importOrderTypeScriptVersion: '5.2.2',
	plugins: ['prettier-plugin-tailwindcss', '@ianvs/prettier-plugin-sort-imports'],
};
