default:
  image: node:21.7.3-alpine

.with-pnpm: &install_pnpm
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir .pnpm-store

.with-npmtoken: &install_package_token
  - echo "@deeev-pro:registry=https://${CI_SERVER_HOST}/api/v4/projects/52187352/packages/npm/">>.npmrc
  - echo "//${CI_SERVER_HOST}/api/v4/projects/52187352/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc


deploy_preview:
  stage: deploy
  except:
    - main
  before_script:
    - *install_pnpm
    - *install_package_token
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  before_script:
    - *install_pnpm
    - *install_package_token
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN