import type { Metadata } from 'next';

import '@/styles/globals.css';
import '@repo/ui/styles';

import React from 'react';

import { Locale } from '@/config/locales';
import { fontClassNames } from '@/config/fonts';
import { cn } from '@repo/ui/utils';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
																		 children,
																		 params,
																	 }: Readonly<{
	children: React.ReactNode;
	params: { locale: Locale };
}>) {
	return (
		<html lang={params.locale}>
		<body className={cn(fontClassNames)}>
		{children}
		</body>
		</html>
	);
}
